version: '3'

services:
  jlab_caiman-workshop23:
    image: wanglabneuro/jlab_caiman:latest
    build: 
      context: ./context
      dockerfile: ./dockerfiles/Dockerfile
    container_name: jupyterlab-caiman
    # environment:
    #   XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
    network_mode: host
    # volumes:
    #   - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # restart: on-failure
