# FROM wanglabneuro/jlab_multi
FROM jupyter/minimal-notebook:hub-3.1.1

LABEL maintainer="Vincent Prevosto <prevosto@mit.edu>"

ENV PATH="/usr/local/MATLAB/R2021b/bin:${PATH}"
# Copy installation files
COPY packages packages
COPY --from=wanglabneuro/matlab_om:2021b /usr/local/MATLAB/R2021b /usr/local/MATLAB/R2021b

USER root
# APT packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    xvfb \
    sshfs \
    fonts-dejavu \
    tzdata \
    scilab && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN fix-permissions $CONDA_DIR && \
fix-permissions /home/$NB_USER && \
fix-permissions /home/$NB_USER/packages/

#Add user to jhub_users group, to get wr permissions to shared folder 
RUN groupadd jhub_users 
RUN usermod -aG jhub_users ${NB_USER}

#Switch to user
USER $NB_UID

# update Anaconda and install pip 
RUN conda update -y conda && \
     conda install -y pip

# Conda installs

RUN conda config --set channel_priority flexible && \
    conda install -y -c conda-forge nb_conda_kernels \
    jupyter_contrib_nbextensions \
    jupyterlab-git \
    pynwb && \
    conda clean -tipy

# Create environments
RUN conda env create -f packages/jmatlab_env.yml 

# Make kernels available
SHELL ["conda","run","-n","jmatlab","/bin/bash","-c"]
RUN python -m ipykernel install --user --name jmatlab --display-name "Matlab" && pip install -U -r packages/jmatlab_requirements.txt 
RUN cd /usr/local/MATLAB/R2021b/extern/engines/python && \
    pip install setuptools==65.7.0 && \
    pip install .

SHELL ["conda","run","-n","base","/bin/bash","-c"]
RUN rm -rf packages

#Switch to user
USER $NB_UID

RUN echo 'alias matlab="/usr/local/MATLAB/R2021b/bin/matlab"' >> ~/.bashrc

# Install Matlab integration for Jupyter
RUN python -m pip install jupyter-matlab-proxy 
RUN conda install jupyter-server-proxy -c conda-forge
